import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Top } from "@/components/pages/top";
import { getMarkdownArticles } from "@/utils";
import { ArticleMeta } from "@/types/article";

type Props = {
  articles: ArticleMeta[];
};

const Home: NextPage<Props> = ({ articles }) => {
  return (
    <>
      <Head>
        <title>Y&#39;s log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Top {...{ articles }} />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<Props> = async () => {
  const articles = await getMarkdownArticles();
  return {
    props: {
      articles,
    },
  };
};
