import type { NextPage } from 'next';
import Head from 'next/head';
import { Top } from '@/components/pages/top';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Y&#39;s log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Top />
    </>
  );
};

export default Home;
