name: Test
on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Env
        run: |
          echo NODE_VERSION=$(cat .tool-versions | sed -e "s/nodejs //g") >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: Install packages
        run: npm ci
      - name: Storybook Startup Test
        run: npm run storybook-startup-test
      - name: Next App Build Test
        run: npx next build
